[package]
name = "Cache-x86"
version = "0.1.0"
authors = ["Yrjo Koyen <yrjo@live.be>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
